name: Build, Publish and Release NPM Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: tsc

      - name: Auto Increment Version
        id: version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          VERSION=$(npm version patch --force -m "Upgrade to %s due to changes")
          echo "::set-output name=tag::$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Changes
        run: |
          git push origin HEAD:main
          git push origin HEAD:main --tags

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "Release Notes:" > release_notes.md
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s" >> release_notes.md
          echo "::set-output name=notes::$(cat release_notes.md)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          body: ${{ steps.release_notes.outputs.notes }}

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
